### ISSUE TITLE
functions failing 'must be the same type' -reading saved dataframes

### ISSUE THREAD

**Issue by benyomin** [benyomin/censusFunctions#10]
Related to other issue:    https://github.com/tidyverse/haven/issues/28

    > weighHouseholds('renters','income')
    Error: `x` and `labels` must be same type
    > subsetByOwnership()
    Error: `x` and `labels` must be same type

There it is claimed that problem is caused by new version of RStudio. Here, I have the problem in ESS.

**Comment by academikuser** [comment]
Now happening on 

     subsetCities()  
after making familiesList based on expFamIndYYYY not famYYYY

**Comment by paynito** [comment]
again, in `subsetCities("addregion")`
these lines are failing

    renters2004 <- renters2004[!renters2004$CODELOC == "Less than 100,000 inhabitants", ]
    renters2004 <<- droplevels(renters2004[!CODELOC == "Less than 50,000 inhabitants", ])

    renters2005 <- renters2005[!renters2005$CODELOC == "Less than 100,000 inhabitants", ]
    renters2005 <<- droplevels(renters2005[!renters2005$CODELOC == "Less than 50,000 inhabitants", ])
